# Quality Profile: 0.30mm (Draft)
[print_settings]
layer_height = 0.30
first_layer_height = 0.3
perimeters = 2
top_solid_layers = 3
bottom_solid_layers = 2
fill_density = 10%
fill_pattern = grid
perimeter_speed = 70
infill_speed = 90
travel_speed = 150
first_layer_speed = 20
gcode_label_objects = octoprint
