# Quality Profile: 0.20mm (Standard)
[print_settings]
layer_height = 0.20
first_layer_height = 0.2
perimeters = 2
top_solid_layers = 4
bottom_solid_layers = 3
fill_density = 15%
fill_pattern = grid
perimeter_speed = 60
infill_speed = 80
travel_speed = 150
first_layer_speed = 20
gcode_label_objects = octoprint
