# Quality Profile: 0.10mm (High Detail)
[print_settings]
layer_height = 0.10
first_layer_height = 0.2
perimeters = 3
top_solid_layers = 5
bottom_solid_layers = 4
fill_density = 20%
fill_pattern = grid
perimeter_speed = 45
infill_speed = 60
travel_speed = 130
first_layer_speed = 20
gcode_label_objects = octoprint
